### ISSUE TITLE
YCM

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-simulator#1]
- [x] `rdSim` script similar to [roboticslab-uc3m/teo-configuration-files/scripts/bash/teoSim](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/762ebe5079e05da38602e21e2feccd9901d8513d/scripts/bash/teoSim), but could invoke python such as: [2 player good for RD](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/blob/develop/examples/python/openraveYarpPluginLoader-robotmanager-rd.py)
- [x] https://github.com/asrob-uc3m/yarp-devices
- [x] https://github.com/roboticslab-uc3m/openrave-yarp-plugins
- [x] https://github.com/asrob-uc3m/robotDevastation-openrave-models

**Comment by jgvictores** [comment]
> rdSim script similar to roboticslab-uc3m/teo-configuration-files/scripts/bash/teoSim, but could invoke python such as:
> 2 player good for RD ((note: same scenario but only 1 robot and no RGD, just depth ))

`scripts/python/rdSim` added at 29fde75dea43999fe04fe22bb9d56a62aa12d2b7

**Comment by PeterBowman** [comment]
YCM done at 06f5035. Also added `.travis.yml`. No AppVeyor support for now until we learn how to properly build OpenRAVE on Windows.

**Comment by jgvictores** [comment]
@PeterBowman Thanks a lot!!! :tada:
